### ISSUE TITLE
Planejamento Inicial do Grupo

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#1]
# Objetivo
Coletar dados dos integrantes a fim de organizar a dinâmica do grupo.

# Atividades
- [x] Criar um forms;
- [x] Organizar os horários de trabalho de cada integrante por meio de uma tabela;
- [x] Estabelecer as plataformas e sites utilizados para estudos.

**Comment by SkywalkerSupreme** [comment]
Aqui está o link do forms que mandei no grupo:
https://docs.google.com/forms/d/e/1FAIpQLSeMvkO9sQZQPijYUvfkYwKJ272b_LeOZSZhmbX8E26VDrviaw/viewform?usp=sf_link

Ainda falta 3 pessoas responderem

**Comment by SkywalkerSupreme** [comment]
Aqui está o link para completar as tabbelas dos horários:
https://docs.google.com/spreadsheets/d/1PRlMzZcP2hacslhfkwKYgXM79_Mq1YnaC8YrAxfJ6Eg/edit?usp=sharing

Respondam de acordo com o nome de vocês
