### ISSUE TITLE
Estudar sobre Arquitetura Monolítica

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#12]
# Objetivo
Como ocorrerá uma mudança de arquitetura no projeto, ficou decidido que mudaremos para uma arquitetura monolítica. Devemos pesquisar melhor sobre e familiarizar os membros do grupo com esse conceito.

# Atividades
- [x] Estudar sobre arquitetura monolítica. Pesquisar prós, contras e como isso pode ser benéfico para o nosso projeto;
- [x] Atualizar o [diagrama de arquitetura](https://github.com/unb-mds/2023-2-Squad02/tree/main/Arquitetura) com a nova arquitetura escolhida;
- [x] Separar materiais de estudos que sejam relevantes e disponibilizar para o grupo;
- [x] Preparar uma explicação breve, que deve ser destinada aos outros membros do grupo.

**Comment by daramariabs** [comment]
**Arquitetura Monolítica: Fundamentos, Vantagens e Desvantagens**

A arquitetura monolítica é um dos modelos arquiteturais mais tradicionais no desenvolvimento de software. Nesse modelo, toda a aplicação é construída como uma única unidade, com todas as funcionalidades, componentes e lógica de negócios integrados em um único código-fonte e implantados como uma única aplicação. Esta abordagem tem características distintas, vantagens e desvantagens que são fundamentais para entender.

**Características da Arquitetura Monolítica:**

1. **Simplicidade:** A arquitetura monolítica é notável pela sua simplicidade. Todo o código e funcionalidades estão contidos em um único código-base, o que facilita o desenvolvimento, a depuração e a manutenção.

2. **Integração Interna:** Todos os componentes de uma aplicação monolítica estão intimamente integrados. Isso significa que a comunicação entre partes do sistema é direta e geralmente baseada em chamadas de funções.

3. **Um Único Ponto de Implantação:** Normalmente, a aplicação monolítica é implantada como uma única unidade. Isso pode tornar a implantação de atualizações e correções um processo mais complexo.

**Vantagens da Arquitetura Monolítica:**

1. **Simplicidade de Desenvolvimento:** A simplicidade da arquitetura monolítica torna o desenvolvimento mais acessível, facilitando a criação de protótipos e aplicativos ágeis.

2. **Facilidade de Manutenção Inicial:** Em estágios iniciais, a manutenção é mais direta, pois todo o código está em um só lugar.

3. **Depuração Simples:** Problemas de depuração tendem a ser mais simples, pois o código está intimamente conectado.

**Desvantagens da Arquitetura Monolítica:**

1. **Escalabilidade Limitada:** A escalabilidade pode ser desafiadora. Quando a demanda por recursos aumenta, é preciso adicionar mais recursos à máquina que executa o aplicativo como um todo.

2. **Manutenção Complexa com o Crescimento:** À medida que o aplicativo cresce e se torna mais complexo, a manutenção pode se tornar problemática. Pequenas alterações podem afetar partes diferentes do código, levando a problemas inesperados.

3. **Dificuldade na Adoção de Novas Tecnologias:** A introdução de novas tecnologias ou atualização de componentes individuais pode ser difícil em uma arquitetura monolítica.

4. **Problemas na Implantação:** A implantação de atualizações ou correções pode ser complicada, pois requer que a aplicação inteira seja implantada novamente.

5. **Tamanho da Equipe:** Uma equipe grande pode ser necessária para gerenciar e manter uma aplicação monolítica complexa.

Em resumo, a arquitetura monolítica é uma escolha adequada para aplicativos de menor complexidade e equipes de desenvolvimento menores, onde a simplicidade inicial e a rápida prototipagem são essenciais. No entanto, à medida que os aplicativos crescem e se tornam mais complexos, a transição para abordagens arquiteturais mais modernas, como a arquitetura orientada a microsserviços, é frequentemente considerada para superar as limitações da arquitetura monolítica.
