### ISSUE TITLE
Organizar a metodologia Scrum

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#16]
# Objetivo
Ao longo do projeto, tentamos seguir alguns dos princípios apontados pelo Scrum como boas práticas. Isso deve ser documentado e disponibilizado.

# Atividades
- [x] Disponibilizar as atas de reuniões;
- [ ] Documentar aqui no repositório as issues que haviam ficado pendentes;
- [ ]

**Comment by SkywalkerSupreme** [comment]
Aqui está a organização das atividades que a gente fez até agora: 

Relatório de Atividade e Execução do Trabalho – Metodologia Scrum
Introdução:
Este relatório descreve a metodologia Scrum aplicada pelo grupo 2 durante as 6 semanas de trabalho no projeto. 

Funções dos integrantes:

Metodologia Scrum: Semanas 1 a 7

Semana 1:
    • Reunião realizada no dia 5 de setembro pelo Discord
    • O que foi discutido na reunião: O grupo se conheceu melhor e pontuou as necessidades do projeto. Além disso, houve a distribuição das tarefas iniciais.
Sprint
    • Planejamento do grupo  = Larissa Stéfane
        ◦ Criar um forms
        ◦ Organizar os horários de trabalho e disponibilidade que cada integrante.
        ◦ Estabelecer algumas outras plataformas de estudo.
    • Estudar parse: Amanda e Dara 
        ◦ Pesquisar sobre parses
        ◦ Realizar um resumo guia
        ◦ Indicar links de sites didáticos
        ◦ Discutir com o grupo sobre os conhecimentos adquiridos.
    • Estudar Git e GitFlow: Alana e Gustavo
        ◦ Pesquisar sobre o que é git e sobre os seus principais comandos.
        ◦ Realizar um resumo guia e disponibilizar nos comentários.
        ◦ Indicar links de dites didáticos e demais referências.
        ◦ Discutir com o grupo sobre os conhecimentos adquiridos.
    • Estudar sobre o projeto “Querido Diário” da Open Knowledge Brasil: Harleny e Isaque
        ◦ Pesquisar sobre “Querido Diário”
        ◦ Pesquisar sobre a OKB
        ◦ Coletar informações sobre os pré-requsitios necessários para desenvolver o projeto.
        ◦ Discutir o assunto com o grupo.
Semana 2:
    • Reunião realizada no dia 13 de setembro pelo Discord
    • O que foi discutido na reunião: Discutimos as tarefas necessárias para atingir nossas metas e sobre o que foi passado na aula no monitor. Além disso, pensar sobre quais estados chamam mais atenção para realizar o trabalho.
        ◦ Principal linguagem que vai ser utilizado na projeto: Python.
Sprint
    • Escolher três possíveis temas para o progeto (Escolher 3 estados do Norte) – Um deles vai ser o tema do projeto: Todos os integrantes
        ◦ O tema do projeto será: Amazonas
    • Estudar o projeto Serenata, que usa uma lógica parecida: Todos os integrantes
    • Pesquisar sobre o funcionamento do site do diário municipal: Alana
    • Apresentação do projeto serenata para usar como inspiração: Dara

Semana 3: 
    • Reunião reaçizada no dia 20 de setembro pelo Discord
    • O que foi discutido na reunião: Foi levado em consideração a utilização do bootstrap.

Sprint
    • Estudo sobre requisitos: Gustavo, Isaque, Larissa
        ◦ Estudar algumas ferramentas e aprendendo a mexer no github.
        ◦ Pesquisar sobre o github projects.
    • Iniciar a extração dos dados: Alana e Harleny
        ◦ Analisar codígos semelhantes.
        ◦ Debugar código do exooneto.
            ▪ Conseguiram extrair arquivos de 2010 até 2020
    • Estudar sobre a metodologia Scrum mais a fundo: Amando e Dara.

Semana 4:
    • Como o grupo não estava conseguindo encontrar um dia para se reunir em chamada de vídeo, a reunião ocorreu pelo whatzapp no dia 28 de setembro.
    • O que foi discutido na reunião: O tema do projeto vai ser licitações.
Sprint
    • Uma das queixas do grupo, foi a dificuldade em entender o funcionamento e a organização do projeto, desse modo, essa semana ficou para estudar e para compreender sobre como funciona a dinâmica de MDS e estudar sobre os pontos em que cada um se encontra com dúvida. - Todos os integrantes
    • Terminar o extrator: Alana e Harleny

Semana 5:
    • Como forma de melhorar a organização do grupo, no dia 4 de outubro foi decidido criar um grupo da turma no teams, onde as reuniões serão realizadas 2 vezes por semana, nas terças e nas quartas às 21:30. No teams, as reuniões serão gravadas.
    • O que foi discutido na reunião: Com a entrega para o dia 11 de outubro, foram declaradas as atividades de cada um.
        ◦ Extrator de dados: Harleny e Alana.
            ▪ Terminar o json por município.
        ◦ Open Source: Amanda e Dara
        ◦ Criar Issues e realizar o store map: Gustavo
        ◦ Realizar design no figma e o diagrama de arquiteura: Larissa
        ◦ Documentação: Isaque e Larissa 
Semana 6:
    • Reunião realizada pelo whatzapp no dia 11 de outubro.
    • O que foi discutido no grupo: Refazer o diagrama de arquitetura, pois estava errado e mudar o designe do site para algo mais parecido com o do exoornero. Além de organizar as outras atividades para a realese 1 (entrega para o dia 25).
Sprint:
    • Refazer o layout no Figma: Harleny
    • Fazer o FORK do projeto: Alana → precisa da permissão da profesora.
    • Fazer o github projects
    • Decidir a tecnologia do front.
    • Refazer as diagramas da arquitetura e realizar a documentação: Larissa 

Semana 7:
    • Reunião realizada no dia 18 de outubro pelo teams.
    • O que foi decidido: É necessário focar mais no front, na metodologia Scrum e sobre as atividades que faltam ser completadas para a release 1. 
Sprint:
    • Organizar a Scrum: Larissa e Gustavo
    • Pesquisar e estudar sobre microserviços: Amanda e Dara
    • Organizar o extrator e criar o fork: Alana
    • Trabalhar no front e documentar as instruções: Isaque e Harleny
