### ISSUE TITLE
Estudar sobre CI/CD

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#31]
# Objetivo
Estudar sobre Continuous Integration e Continuous Delivery e expor formas de aplicar seus conceitos aqui na disciplina.

# Atividades
- [x] Pesquisar sobre CI/CD. Principais conceitos e aplicações, formas de implementar, etc;
- [x] Realizar um resumo guia e disponibilizá-lo;
- [x] Indicar links de sites didáticos e demais referências;
- [x] Discutir com o grupo sobre os conhecimentos adquiridos.

**Comment by alanagabriele** [comment]
Objetivo do CI/CD
Continuous Integration (CI): Prática de integrar automaticamente o código-fonte em um repositório centralizado várias vezes ao dia. O principal objetivo é detectar problemas cedo, facilitando a integração de mudanças.
Continuous Delivery (CD): Extensão do CI para garantir que além de integrar as mudanças, o software possa ser liberado para produção a qualquer momento de forma rápida e eficiente.

**Comment by alanagabriele** [comment]
Principais Conceitos e Aplicações
Automação de Build e Testes: No CI, após o código ser enviado para o repositório, um sistema de build automático compila o código e executa uma série de testes para garantir a qualidade.
Feedback Rápido: CI/CD permite que as equipes recebam feedback rápido sobre as mudanças, reduzindo os custos de correção de bugs e melhorando a qualidade do software.
Deployment Automatizado: No CD, após a fase de integração, o software é automaticamente preparado para a implantação, que pode ser feita com um clique ou automaticamente.

**Comment by alanagabriele** [comment]
Formas de Implementar
Escolha de Ferramentas: Jenkins, GitLab CI, CircleCI, Travis CI, e GitHub Actions são algumas das ferramentas populares para implementar CI/CD.
Pipeline de CI/CD: Configurar um pipeline que inclui etapas como checkout de código, build, testes automatizados, e deployment.
Infraestrutura como Código (IaC): Utilizar práticas de IaC para gerenciar e provisionar infraestrutura através de código, facilitando a automação.

**Comment by alanagabriele** [comment]
Local para estudos

Coursera: Oferece cursos online de universidades renomadas sobre CI/CD, muitas vezes com opções de acesso gratuito a materiais de curso.

Udemy: Uma plataforma de aprendizado online com uma vasta gama de cursos sobre práticas de CI/CD, frequentemente ministrados por profissionais da indústria.

Pluralsight: Conhecida por seus cursos de tecnologia, oferece treinamento específico em ferramentas e práticas de CI/CD.

edX: Outra plataforma de cursos online que oferece cursos de instituições respeitadas sobre tópicos de engenharia de software, incluindo CI/CD.

GitHub Learning Lab: Fornece uma série de cursos práticos para aprender sobre o uso do Git, que é fundamental para a CI.

Codecademy: Oferece cursos interativos que podem incluir tópicos relacionados a CI/CD.
