### ISSUE TITLE
Estudar sobre Testes de Software

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#32]
# Objetivo
Testar o código e suas funcionalidades é algo essencial no trabalho de um engenheiro de software, portanto precisamos entender melhor sobre esse conceito e como podemos aplicá-lo no nosso projeto. 

# Atividades
- [x] Pesquisar sobre Testes de Software. Principais conceitos e aplicações, formas de implementar, etc;
- [x] Realizar um resumo guia e disponibilizá-lo;
- [x] Indicar links de sites didáticos e demais referências;
- [x] Discutir com o grupo sobre os conhecimentos adquiridos.

**Comment by acamposs** [comment]
##  Testes de Software

**O que são Testes de Software?**
Os testes de software são procedimentos sistemáticos para verificar se um programa funciona conforme o esperado. Eles são essenciais para garantir a qualidade e confiabilidade do software.

**Por que Testar?**
1. **Identificação de Bugs:** Os testes ajudam a encontrar e corrigir erros antes que o software seja lançado.
2. **Manutenção Mais Fácil:** Um conjunto sólido de testes facilita a manutenção e evolução do software.
3. **Confiança no Código:** Testes bem-sucedidos dão confiança de que as funcionalidades existentes não foram quebradas por alterações no código.

## Tipos de Testes de Software

1. **Testes Unitários:**
   - Focados em unidades individuais de código (funções, métodos).
   - Garantem que cada parte do software funcione conforme o esperado.

2. **Testes de Integração:**
   - Verificam a interação entre diferentes partes do sistema.
   - Certificam-se de que os componentes se integram corretamente.

3. **Testes Funcionais:**
   - Testam o software como um todo, verificando se as funcionalidades atendem aos requisitos.

## Pytest

**O que é Pytest?**
Pytest é uma estrutura de teste em Python que facilita a escrita e execução de testes. Ele é amplamente utilizado e apreciado pela sua simplicidade e poder.

**Vantagens do Pytest:**
1. **Sintaxe Simples:** A sintaxe do Pytest é limpa e fácil de entender, o que facilita a escrita dos testes.
2. **Detecta Automaticamente Testes:** Pytest encontra automaticamente e executa os testes no seu projeto.
3. **Suporte a Testes Parametrizados:** Permite executar o mesmo teste com diferentes conjuntos de dados.
4. **Plugins Extensíveis:** A funcionalidade do Pytest pode ser estendida através de plugins, se necessário.

## Como Usar Pytest no nosso Projeto

1. **Instalação:**
   ```bash
   pip install pytest

2. **Estrutura de Diretórios:**
   - Coloque os arquivos de teste no mesmo diretório ou em um diretório chamado `tests`.

3. **Escrevendo Testes:**
   - Crie funções de teste começando com `test_`.
   - Use assert para verificar se o código funciona conforme o esperado.

   Exemplo:
   ```python
   # test_calculadora.py

   def test_soma():
       assert soma(2, 3) == 5
4. **Executando Testes:**
    - Execute todos os testes no terminal:
    ```bash
    pytest
    ```
    
    - Execute um teste específico:
    ```bash
    pytest test_calculadora.py::test_soma
    ```

**Conclusão:**
Implementar testes de software e adotar o Pytest em nosso projeto Python nos ajudará a garantir a qualidade do código, detectar problemas precocemente e manter a confiança no desenvolvimento do software.
