### ISSUE TITLE
Estudar sobre Extreme Programming

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#33]
# Objetivo
O Extreme Programming é uma metodologia bastante utilizada em projetos de software nos dias de hoje. Já que foi antecipado que iremos trabalhar com ela na disciplina, devemos entender melhor do que se trata. 

# Atividades
- [x] Pesquisar sobre XP. Principais conceitos e aplicações, formas de implementar, etc;
- [x] Realizar um resumo guia e disponibilizá-lo;
- [x] Indicar links de sites didáticos e demais referências;
- [x] Discutir com o grupo sobre os conhecimentos adquiridos.

**Comment by SkywalkerSupreme** [comment]
# Pesquisa sobre XP (Extreme Programming)

## Valores Fundamentais da XP:

Explorar os valores essenciais da XP, como Comunicação, Simplicidade, Feedback e Coragem, que moldam a cultura e as práticas da metodologia.

## Práticas-Chave:

Investigar práticas emblemáticas da XP, como Desenvolvimento Orientado a Testes (TDD), Integração Contínua, Refatoração e Programação em Par. Entender como essas práticas se integram para promover um desenvolvimento ágil e de alta qualidade.

## Aplicações e Casos de Sucesso:

Analisar casos de sucesso onde a XP foi implementada com êxito, destacando os benefícios alcançados e os desafios superados. Isso ajudará a visualizar a aplicabilidade prática da metodologia em diferentes contextos.

## Formas de Implementação:

Explorar diferentes abordagens para implementar a XP, considerando fatores como tamanho da equipe, tipo de projeto e cultura organizacional. Avaliar as adaptações possíveis para melhor atender às necessidades específicas do nosso projeto.

**Comment by SkywalkerSupreme** [comment]
Estou entusiasmada com essa pesquisa e acredito que a compreensão aprofundada da XP pode agregar significativamente ao nosso projeto.

**Comment by SkywalkerSupreme** [comment]
## Links de site de estudo:

Dicas de alguns sites que achei interessante

**Metodologia Ágil - O que é?** : https://www.alura.com.br/artigos/o-que-e-metodologia-agil?utm_term=&utm_campaign=%5BSearch%5D+%5BPerformance%5D+-+Dynamic+Search+Ads+-+Artigos+e+Conte%C3%BAdos&utm_source=adwords&utm_medium=ppc&hsa_acc=7964138385&hsa_cam=11384329873&hsa_grp=111087461203&hsa_ad=682526577071&hsa_src=g&hsa_tgt=aud-1636998483065:dsa-843358956400&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiApuCrBhAuEiwA8VJ6JsLu09hTDUUnJgxAhwEBCa-iNIPODOK61DVTUJ1Be57elrR_bXBIOBoCelIQAvD_BwE


**Metodologia ágil: definição, benefícios e como implementar na sua empresa** : https://blog.runrun.it/metodologia-agil/#:~:text=A%20metodologia%20%C3%A1gil%20%C3%A9%20um,surgem%20as%20necessidades%20do%20cliente.
