### ISSUE TITLE
Estudar e verificar um novo tema para o projeto

### ISSUE THREAD

**Issue by daramariabs** [unb-mds/2023-2-Squad02-Desmatazonia#35]
## Implementação da Segunda Etapa - Extração e Monitoramento de Informações Relevantes

Para tornar mais fácil o acompanhamento, o projeto foi dividido em duas fases. 

1.  A primeira fase tem como principal objetivo propor e avaliar um algoritmo que permita a separação do conteúdo do diário oficial da Associação Amazonense de Municípios (AAM) por município. Essa fase foi executada com sucesso para a primeira Realese. Seu objetivo foi coletar, transformar em texto e separar em municípios.

2.  A segunda fase diz respeito a extração e monitoramento de informações relevantes onde o texto do diário de cada ente estadual é separado em atos normativos.

**Descrição:**

O objetivo desta issue é coordenar a implementação da segunda fase da extração de dados, que consiste na extração e monitoramento de informações relevantes no diário oficial da Associação Amazonense de Municípios (AAM).

**Tarefas:**

1. **Escolha e Decisão das Informações Relevantes:**
   - [x] Realizar uma revisão das informações disponíveis no diário oficial da AAM.
   - [x] Identificar as informações mais relevantes para o projeto, considerando o escopo inicial e os objetivos do monitoramento.

3. **Estudo para a Execução da Segunda Fase a partir da Primeira:**
   - [x] Analisar os resultados da primeira fase, que envolveu a separação do conteúdo por município no diário oficial da AAM.
   - [x] Identificar padrões e estruturas nos dados já extraídos para facilitar a implementação da segunda fase.
   - [x] Considerar ajustes ou melhorias necessárias na estrutura de dados obtida na primeira fase para atender aos requisitos da segunda etapa.

5. **Desenvolvimento e Implementação:**
   - [x] Iniciar o desenvolvimento do código para extração e monitoramento das informações relevantes.
   - [x] Integrar os resultados da segunda fase aos dados já obtidos na primeira fase, garantindo consistência e continuidade do projeto.

6. **Testes e Validação:**
   - [x] Realizar testes rigorosos para garantir a precisão e confiabilidade da extração de informações relevantes.
   - [x] Validar os resultados obtidos comparando-os com fontes confiáveis e esperadas.

7. **Documentação:**
   - [x] Manter uma documentação clara e atualizada do processo de extração de dados, incluindo escolhas de informações relevantes, ajustes feitos com base na análise da primeira fase, e detalhes de implementação.

**Critérios de Aceitação:**
- [x] As informações relevantes estão sendo extraídas com precisão.
- [x] A execução da segunda fase é eficiente e integrada à estrutura da primeira fase.
- [x] Testes passam com sucesso, garantindo a confiabilidade dos resultados.

**Observações:**
- Esta issue servirá como guia para o desenvolvimento da segunda etapa do projeto. Se necessário, atualizações e discussões adicionais podem ser realizadas aqui.
- Essa issue sera subdividida em outras issues para que a realização dela seja distribuída entre o time e que seja eficiente
- As sugestões de temas podem ser colocadas nos comentários dessa issue

**Comment by acamposs** [comment]
O link fornecido pela professora no dia da apresentação para o acesso a base de dados dos diarios oficiais estruturada:

https://basedosdados.org

**Comment by acamposs** [comment]
Algumas sugestões de temas que achei interessantes no link:

- [Desmatamento PRODES](https://basedosdados.org/dataset/e5c87240-ecce-4856-97c5-e6b84984bf42?table=d7a76d45-c363-4494-826d-1580e997ebf0) - O projeto PRODES realiza o monitoramento por satélites do desmatamento por corte raso na Amazônia Legal e produz, desde 1988, as taxas anuais de desmatamento na região, que são usadas pelo governo brasileiro para o estabelecimento de políticas públicas. 

- [Autorização de Exploração Florestal](https://basedosdados.org/dataset/9be51b5f-491a-4184-82e4-e75089beb2b9?raw_data_source=b95cdf6d-bd95-4eab-9f7f-bf7a80b782e6) - Relação de Autorizações de Exploração Florestal (Autex) cadastradas no sistema do Documento de Origem Florestal (DOF), contendo dados sobre produtos, espécies, volumes autorizados e volumes remanescentes, entre outros.

- [Amazônia Minada](https://basedosdados.org/dataset/a294578d-62e5-4ab1-80ad-0c9e049362a0?raw_data_source=6724b665-54a9-4729-8f19-ea623046f8c0) - Pedidos de mineração dentro de áreas protegidas recebem aval do governo.

- [Sistema de Detecção de Desmatamentos em Tempo Real (DETER)](https://basedosdados.org/dataset/52d4efbf-9d1a-4dd0-8558-414bd0fe4124?raw_data_source=50de1cc4-0b3b-44ff-a31e-44f6f6f498c2) - O DETER é um levantamento rápido de alertas de evidências de alteração da cobertura florestal na Amazônia, feito pelo INPE. 

o que eu mais gostei foi o da Amazonia Minada!!

**Comment by daramariabs** [comment]
Ficou estabelecido que iremos utilizar a base de dados de Desmatamento do PRODES.

**Comment by acamposs** [comment]
### Escolha do tema

Após análise de todas as bases de dados sugeridas, optamos escolher a base de dados referente ao [Desmatamento PRODES](https://basedosdados.org/dataset/e5c87240-ecce-4856-97c5-e6b84984bf42?table=d7a76d45-c363-4494-826d-1580e997ebf0).

**Características relevantes para a escolha da base de dados:**

1. Base de dados já tratada
2. Informações pertinentes para realizar as buscas e gerar os gráficos
3. Municípios como nível de observação
4. Cobertura temporal grande e atual

**Comment by acamposs** [comment]
Essa issue foi transformada em um sprint para que o desenvolvimento dela seja melhor aproveitado pelo time. A sprint designada é a Sprint 9.
