### ISSUE TITLE
Documentar planejamento da sprint 9

### ISSUE THREAD

**Issue by daramariabs** [unb-mds/2023-2-Squad02-Desmatazonia#36]
Relatar planejamento da sprint, seguindo o padrão já existente no Gitpages.

**Comment by SkywalkerSupreme** [comment]
### Sprint 9

Realizada após a aula durante a manhã e outra no teams pela noite no dia 08/11/2023

**Objetivo da reunião:** Continuar a discurssão sobre a organização das pesquisas para o desenvolvimento da segunda etapa do projeto e procurar por uma nova base de dados mais atualizada sobre o meio ambiente no Amazonas.

**Planing**

- Pesquisar por uma nova base de dados: Larissa Stéfane e Gustavo
- Estudar e iniciar os testes: Isaque Santos, Amanda e Dara
- Continuar a desenvolver o front: Harleny e Alana
- Documentar sprint: Larissa Stéfane
