### ISSUE TITLE
Refatorar busca de dados

### ISSUE THREAD

**Issue by daramariabs** [unb-mds/2023-2-Squad02-Desmatazonia#38]
## Descrição

Atualmente, a funcionalidade de busca em nosso site enfrenta desafios significativos, resultando em uma experiência do usuário abaixo do ideal. Esta issue destina-se a propor a refatoração completa da funcionalidade de busca para melhorar a precisão, a velocidade e a usabilidade.

## Tarefas

- [x] Realizar uma análise aprofundada dos problemas existentes na funcionalidade de busca.
- [x] Pesquisar e avaliar algoritmos de busca mais avançados.
- [x] Otimizar as consultas ao banco de dados para melhorar a velocidade.
- [x] Projetar e implementar novos recursos para enriquecer a funcionalidade de busca.

## Critérios de Aceitação

- Os resultados da busca devem ser mais precisos e relevantes.
- A velocidade de resposta da busca deve ser otimizada.
- Novos recursos, como filtros e opções de ordenação, devem ser implementados com sucesso.

**Comment by SkywalkerSupreme** [comment]
# Busca por sites que apresentam dados e PDFs atualizados:

### Portal da transparência do Amazonas: Disponível em [link](https://www.transparencia.am.gov.br/)
### Secretária do Meio Ambiente: Disponível em [link](https://meioambiente.am.gov.br/downloads/)
### Imprensa Oficial do Amazonas: Disponível em [link](https://diario.imprensaoficial.am.gov.br/)
### Diário Oficial ELetrônico do Amazonas: Disponível em [link](https://diariomunicipalaam.org.br/)

**Comment by SkywalkerSupreme** [comment]
# SOBRE A BUSCA DE DADOS:

Para desenvolver um algoritmo de busca, são necessários alguns passos:

## Passo 1:  Criar um Crawler:

O primeiro passo para criar um mecanismo de busca, seja ele vertical ou genérico, é desenvolver um crawler ou spider. Isso porque, essa ferramenta automatizada coleta informações de uma fonte de dados específica e as organiza em um índice. 
Desse modo, sem o trabalho do crawler, é impossível ter um mecanismo de busca eficiente, pois ele facilita a organização da busca e, se executado periodicamente, pode manter a base de dados atualizada.

### Código do crawler:


	          pip install PyPDF2
          
	          import os
                  import PyPDF2
                  
                  def extrair_texto_de_pdf(caminho_do_pdf):
                      texto = ""
                  
                      with open(caminho_do_pdf, "rb") as arquivo_pdf:
                          leitor_pdf = PyPDF2.PdfFileReader(arquivo_pdf)
                  
                          # Iterar sobre todas as páginas do PDF
                          for pagina_numero in range(leitor_pdf.numPages):
                              pagina = leitor_pdf.getPage(pagina_numero)
                              texto += pagina.extractText()
                  
                      return texto
                  
                  def crawler_pdf_dados_licitacoes(diretorio_pdfs):
                      dados_licitacoes = []
                  
                      # Iterar sobre todos os arquivos no diretório
                      for nome_arquivo in os.listdir(diretorio_pdfs):
                          if nome_arquivo.endswith(".pdf"):
                              caminho_completo = os.path.join(diretorio_pdfs, nome_arquivo)
                  
                              # Extrair texto do PDF
                              texto_pdf = extrair_texto_de_pdf(caminho_completo)
                  
                              # Adicionar dados extraídos à lista
                              dados_licitacoes.append({
                                  "nome_arquivo": nome_arquivo,
                                  "texto_pdf": texto_pdf
                              })
                  
                      return dados_licitacoes
                  
                  # Exemplo de uso
                  diretorio_pdfs = "/caminho/do/seu/diretorio"
                  dados_licitacoes = crawler_pdf_dados_licitacoes(diretorio_pdfs)
                  
                  # Exibir resultados
                  for licitacao in dados_licitacoes:
                      print(f"Nome do Arquivo: {licitacao['nome_arquivo']}")
                      print(f"Texto do PDF: {licitacao['texto_pdf']}")
                      print("=" * 50)
                  
## Passo 2: Criar um índice:

Ao ler as informações coletadas pelo crawler, o próximo passo é criar um índice, que contém dados relevantes para a busca. Nesse quesito, índices invertidos são comuns em mecanismos de busca baseados em texto. 

Inicialmente, um forward index é criado, associando identificadores únicos a conjuntos de tags. Em seguida, o índice invertido é construído, relacionando cada tag aos registros em que aparecem. Considerações adicionais, como pesos para tags e densidade de palavras, podem ser incorporadas para melhorar a relevância dos resultados.

### Código de índice invertido:

                from collections import defaultdict
            import os
            import PyPDF2
            import re
            
            def extrair_texto_de_pdf(caminho_do_pdf):
                texto = ""
            
                with open(caminho_do_pdf, "rb") as arquivo_pdf:
                    leitor_pdf = PyPDF2.PdfFileReader(arquivo_pdf)
            
                    # Iterar sobre todas as páginas do PDF
                    for pagina_numero in range(leitor_pdf.numPages):
                        pagina = leitor_pdf.getPage(pagina_numero)
                        texto += pagina.extractText()
            
                return texto
            
            def criar_indice_invertido(diretorio_pdfs):
                indice_invertido = defaultdict(list)
            
                # Iterar sobre todos os arquivos no diretório
                for nome_arquivo in os.listdir(diretorio_pdfs):
                    if nome_arquivo.endswith(".pdf"):
                        caminho_completo = os.path.join(diretorio_pdfs, nome_arquivo)
            
                        # Extrair texto do PDF
                        texto_pdf = extrair_texto_de_pdf(caminho_completo)
            
                        # Limpar o texto (remover caracteres especiais, espaços em branco extras, etc.)
                        texto_limpo = re.sub(r'[^a-zA-Z0-9\s]', '', texto_pdf)
            
                        # Tokenização (dividir o texto em palavras)
                        palavras = texto_limpo.lower().split()
            
                        # Construir o índice invertido
                        for posicao, palavra in enumerate(palavras):
                            indice_invertido[palavra].append({
                                "nome_arquivo": nome_arquivo,
                                "posicao": posicao + 1  # Adicionar 1 para evitar posição zero
                            })
            
                return indice_invertido
            
            # Exemplo de uso
            diretorio_pdfs = "/caminho/do/seu/diretorio"
            indice_invertido = criar_indice_invertido(diretorio_pdfs)
            
            # Exibir resultados para uma palavra específica (ajuste conforme necessário)
            palavra_pesquisada = "meio"
            if palavra_pesquisada in indice_invertido:
                print(f"Ocorrências da palavra '{palavra_pesquisada}':")
                for ocorrencia in indice_invertido[palavra_pesquisada]:
                    print(f"  - Arquivo: {ocorrencia['nome_arquivo']}, Posição: {ocorrencia['posicao']}")
            else:
                print(f"A palavra '{palavra_pesquisada}' não foi encontrada no índice invertido.")

## Passo 3: Criar um algoritmo de Busca:

Com o índice pronto, é necessário desenvolver um algoritmo de busca. Assim, esse algoritmo varia dependendo do tipo de busca desejado. 

Em uma busca textual, por exemplo, a entrada do usuário é normalizada e dividida em tags. Posteriormente, o algoritmo procura registros associados a cada tag e, em seguida, realiza a interseção desses conjuntos para obter resultados precisos. 

*Observação:* A precisão do algoritmo pode variar, permitindo diferentes níveis de flexibilidade na pesquisa.

### Algoritmo de busca:

          def buscar_no_indice_invertido(indice_invertido, consulta):
              consulta = consulta.lower()
              palavras_chave = consulta.split()
          
              resultados = []
              for palavra in palavras_chave:
                  if palavra in indice_invertido:
                      resultados.extend(indice_invertido[palavra])
          
              # Ordenar resultados por nome do arquivo e posição
              resultados = sorted(resultados, key=lambda x: (x['nome_arquivo'], x['posicao']))
          
              return resultados
          
          # Exemplo de uso
          consulta_do_usuario = "licença ambiental"
          resultados_da_busca = buscar_no_indice_invertido(indice_invertido, consulta_do_usuario)
          
          # Exibir resultados
          if resultados_da_busca:
              print(f"Resultados para a consulta '{consulta_do_usuario}':")
              for resultado in resultados_da_busca:
                  print(f"  - Arquivo: {resultado['nome_arquivo']}, Posição: {resultado['posicao']}")
          else:
              print(f"Nenhum resultado encontrado para a consulta '{consulta_do_usuario}'.")

## Passo 4: Aperfeiçoar:

Mesmo após a implementação inicial, é crucial aprimorar continuamente o mecanismo de busca. O que pode ser feito com feedback dos usuários, coleta de dados de uso, e a observação do comportamento dos usuários são essenciais.
	
Para isso, ferramentas como Net Promoter Score (NPS) e gravadores de sessão podem fornecer insights valiosos.

**Comment by SkywalkerSupreme** [comment]
Link do site que utilizei para fazer as pesquisas:

https://repositorio.ufsc.br/handle/123456789/184228

https://rockcontent.com/br/blog/algoritmo-do-google/

https://www.luiztools.com.br/post/como-criar-um-mecanismo-de-busca/
