### ISSUE TITLE
Documentar planejamento da sprint 8

### ISSUE THREAD

**Issue by daramariabs** [unb-mds/2023-2-Squad02-Desmatazonia#39]
Relatar planejamento da sprint, seguindo o padrão já existente no Gitpages.

**Comment by SkywalkerSupreme** [comment]
# Reunião do dia 02/11/2023

## Sumário
* [Dados](#Dados)
* [Participantes](#Participantes)
* [Discussão](#Discussão)
* [Decisões](#Decisões)
* [Histórico de Versões](#Histórico-de-Versões)

## Dados
Informações sobre data, local e duração:

• **Data:** 02/11/2023

• **Local:** Grupo do Whatzapp - Devido a uma série de divergências, o grupo decidiu que, para esta semana, seria melhor a reunião ocorrer pelo whatzapp do que pelo teams.

• **Duração:** Começou no dia 28/10 e terminou no dia 02/11.

## Participantes

• Alana Gabriele

• Amanda Campos

• Dara Maria

• Gustavo Lima

• Harleny Angelica

• Isaque Santos

• Larissa Stéfane

## Discussão

Na reunião realizada via WhatsApp, o nosso grupo avaliou o andamento do projeto e identificou pontos cruciais que demandam atenção para prosseguirmos.

Uma das principais questões em discussão é a necessidade de mudar o tema do projeto para explorar a relação do Meio Ambiente no Amazonas, mas não sabemos em que contexto ainda. Como essa decisão requer uma análise aprofundada foi decidido que será um ponto de discussão crucial que ocorrerá na próxima reunião por vídeo conferência. Além disso, discutimos a importância de definir pesquisas e informações necessárias para sustentar o progresso do desenvolvimento.

**Conclusão:** Conscientes da necessidade de aprofundamento, tomamos a decisão de dividir responsabilidades entre os membros do grupo. Dese modo, cada um de nós se comprometeu a estudar assuntos e conceitos específicos ao longo da próxima semana, a fim de reunir informações valiosas para as decisões futuras. 

## Decisões

| Identificador (Issue n) | Issue                                                                     | Integrante(s) responsável(eis) | Pontos |
|-------------------------|---------------------------------------------------------------------------|--------------------------------|--------|
| Issue 1                 | Estudar e pesquisar a integração contínua (CI) e a entrega contínua (CD). | Alana Gabriele                 |7       |
| Issue 2                 | Pesquisar e explorar o conceito de Extreme Programming (XP)               | Gustavo Lima                   | 7      |
| Issue 3                 | Estudo na área de testes                                                  | Amanda Campos                  | 7      |
| Issue 4                 |  Pesquisar e compreender o conceito de contêineres                        | Larissa Stéfane                | 7      |


<p align="center"> Tabela 1. Issues Sprint  </p>

##  Histórico de Versão

| Versão | Alteração              | Responsável      | Revisor            | Data  |
|--------|------------------------|------------------|--------------------|-------|
| 1.0    | Criação Ata da Reunião | Larissa Stéfane | Larissa Stéfane   | 02/11 |
