### ISSUE TITLE
Coelho de Container

### ISSUE THREAD

**Issue by daramariabs** [unb-mds/2023-2-Squad02-Desmatazonia#40]
Objetivo: Estudar sobre a metodologia Conteiner e verificar como ela pode ajudar no nosso projeto!

- [x] Definir o que é um conteiner
- [x] Definir como ela pode ajudar no nosso projeto

**Comment by SkywalkerSupreme** [comment]
# contêineres

## Sumário
* [O que é?](#O-que-é?)
* [Analogia](#Analogia)
* [Importância](#Importância)
* [Conceitos Chaves](#Conceitos-Chaves)
* [Sites para Estudo](#Sites-para-Estudo)
* [Vídeos para Estudo](#Vídeos-para-Estudo)
* [Histórico de Versão](#Histórico-de-Versão)

## O que é?

Primeiramente, um contêiner, em termos de programação e de computação, é uma unidade de software a qual contém um aplicativo ou unidade de desenvolvimento junto com todas as suas dependências necessárias, incluindo bibliotecas, arquivos de configuração e recursos. Desse modo, essa unidade é projetada para ser auto-suficiente e isolada, o que significa que o aplicativo dentro do contêiner pode ser executado de maneira consistente e previsível, independentemente do ambiente em que está sendo executado. Devido a isso, é permitido que o aplicativo seja executado consistentemente em diferentes sistemas, independentemente das diferenças na infraestrutura.

## Analogia

Eles são semelhantes a "caixotes" de navios, onde cada contêiner tem uma função e uma responsabilidade isolada. Consequentemente, se um contêiner falhar, o sistema continua funcionando, redirecionando a função afetada para um novo contêiner.

## Importância

A adoção de contêineres é importante devido à sua capacidade de economizar recursos, oferecer maior disponibilidade, adaptar-se a picos de tráfego e simplificar a manutenção.

## Conceitos chaves

### Docker
  Uma maneira de criar, implantar e gerenciar contêineres é utilizando a plataforma Docker, uma das plataformas mais populares e amplamente utilizadas para esta área. Dessa maneira, com ela, é possível empacotar o aplicativo juntamente com todas as suas bibliotecas e com as suas  dependências necessárias, que permite que ele seja ser executado em qualquer lugar que tenha o Docker instalado.

### Imagem de Contêneir

  É uma representação estática de um aplicativo e suas dependências. Assim, ela contém tudo o que é necessário para executar o aplicativo, incluindo o código, as bibliotecas e as configurações.

### Orquestração de Contêineres

  São necessárias algumas ferramentas para gerenciar e escalar os contêineres em um ambiente de produção, como os Kubernetes. Assim, os Kubernetes  permitem que a implantação seja balanceada, o que garante o balanceamento de carga e a recuperação de falhas de contêineres.

### Portabilidade

  Uma das vantagens dos contêiners é que eles são altamente portáteis, o que significa que é possível criar um contêiner em uma máquina e executá-lo em outra, independentemente do sistema operacional ou da infraestrutura subjacente.

### Isolamento

  Eles oferecem isolamento entre diversos aplicativos e as suas dependências, o que garante que eles não afetem uns aos outros.

### Eficiência

  Eles são eficientes em termos de recursos, uma vez que compartilham o kernel do sistema operacional hospedeiro e consomem menos recursos do que máquinas virtuais tradicionais.

## Sites para Estudo
  
 • Containers: O que são no mundo da programação?. Disponível em: [link](https://www.hostgator.com.br/blog/containers-o-que-sao-no-mundo-da-programacao/)
 
 • Afinal, o que é um container?.  Disponível em: [link](https://www.treinaweb.com.br/blog/afinal-o-que-e-um-container)
 
 • Containers and Docker: what they are and how to use them. Disponível em: [link](https://esr.rnp.br/administracao-de-sistemas/containers-docker-como-utilizar/)

## Vídeos para Estudo

 • Containers // Dicionário do Programador. Disponível em: [link](https://www.youtube.com/watch?v=-pUZBovqRcU)
 
 • Container e Docker - para iniciantes. Disponível em: [link](https://www.youtube.com/watch?v=HCfvhDhiK98)

##  Histórico de Versão

| Versão | Alteração | Responsável | Revisor | Data |
| - | - | - | - | - |
| 1.0 | Estudo sobre Contêiner | Larissa Stéfane | - | 02/11/2023

**Comment by SkywalkerSupreme** [comment]
## Como o uso de conteiner pode ajudar no nosso projeto:

No desenvolvimento do nosso projeto de extração de dados sobre o desmatamento na Amazônia, o uso de contêineres pode desempenhar um papel crucial na otimização da eficiência e  na consistência do ambiente de desenvolvimento. 
Ao empregar contêineres, é possível  garantir uma abordagem isolada e padronizada para a execução do nosso extrator de dados.
