### ISSUE TITLE
Escolha e Decisão das Informações Relevantes

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#42]
## Descrição:
Esta tarefa visa realizar a revisão das informações disponíveis no diário oficial da AAM e identificar as mais relevantes para o projeto de extração de dados. Isso inclui nomeações, exonerações e outras informações pertinentes à análise.

### Tarefas:
- [x] Realizar uma revisão abrangente das informações presentes no diário oficial da AAM.
- [x] Identificar e listar as informações mais relevantes para o projeto, considerando o escopo inicial e os objetivos de monitoramento.

**Comment by daramariabs** [comment]
Após reunião com @acamposs chegamos ao consenso de que os dados extraídos dos diarios até a presente data não fazem mais sentido para a segunda fase do projeto.
