### ISSUE TITLE
Estudo para a Execução da Segunda Fase a partir da Primeira

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#43]
## Descrição:
Esta tarefa envolve a análise dos resultados da primeira fase, especificamente a separação do conteúdo por município no diário oficial da AAM. O objetivo é identificar padrões e estruturas nos dados já extraídos, além de considerar ajustes ou melhorias necessárias na estrutura de dados para atender aos requisitos da segunda etapa.

### Tarefas:
- [x] Analisar os resultados da primeira fase, destacando padrões e estruturas presentes nos dados.
- [x] Identificar possíveis melhorias na estrutura de dados obtida na primeira fase para facilitar a implementação da segunda etapa.
- [x] Considerar ajustes necessários na estrutura de dados para garantir consistência e continuidade do projeto.

**Comment by daramariabs** [comment]
Após reunião com @acamposs chegamos ao consenso de que os dados extraídos dos diarios até a presente data não fazem mais sentido para a segunda fase do projeto.
