### ISSUE TITLE
Desenvolvimento e Implementação

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#44]
## Descrição:
Esta tarefa concentra-se no desenvolvimento do código para a extração e monitoramento das informações relevantes no diário oficial da AAM. Deve-se garantir que os resultados da segunda fase sejam integrados aos dados já obtidos na primeira fase, mantendo a consistência e a continuidade do projeto.

### Tarefas:
- [x] Iniciar o desenvolvimento do código para a extração e monitoramento das informações relevantes.
- [x] Integrar os resultados da segunda fase aos dados já obtidos na primeira fase.
- [x] Garantir que a execução da segunda fase seja eficiente e esteja integrada à estrutura da primeira fase.

**Comment by daramariabs** [comment]
Não usaremos mais os dados retirados dos diários oficiais.

**Comment by daramariabs** [comment]
Utilizaremos a base de desmatamento do PRODES. 

- Realizei a extração dos dados
- Refatorei a base de dados de modo que tenhamos somente informações do estado do Amazonas
