### ISSUE TITLE
Refatoração do Site para Receber Nova Base de Dados

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#47]
## Descrição:
Esta tarefa concentra-se na avaliação da estrutura atual do site para identificar áreas que requerem refatoração, a fim de acomodar a nova base de dados proveniente da segunda fase do extrator de dados. Isso inclui a atualização de esquemas e modelos de dados no front-end, garantindo consistência visual e funcional com as novas informações.

### Tarefas:
- [x] Avaliar a estrutura atual do site para identificar áreas que requerem refatoração.
- [x] Atualizar esquemas e modelos de dados no front-end para incorporar as informações extraídas na segunda fase.
- [x] Garantir consistência visual e funcional com as novas informações.

**Comment by daramariabs** [comment]
Depois de analisar o front fiz ajustes necessários para que as informações ficassem mais coerentes.
