### ISSUE TITLE
Definição do Resultado de Busca nos Gráficos do Site

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#48]
## Descrição:
Esta tarefa visa determinar a quantidade e os temas dos gráficos necessários para representar os resultados da segunda fase de extração no front-end do site. Os temas dos gráficos serão identificados com base nas informações extraídas, como o número de eventos por município, a evolução ao longo do tempo, os municípios mais impactados, etc.

### Tarefas:
- [x] Determinar a quantidade de gráficos necessários para representar os resultados da segunda fase.
- [x] Identificar os temas dos gráficos com base nas informações extraídas.
- [x] Integrar os gráficos de forma intuitiva e acessível no site.

**Comment by alanagabriele** [comment]
Foi decidido a utilização de 3 gráficos: gráfico de barra mostrando os dados com o passar dos anos municipio escolhido, gráfico de pizza mostrando a porcentagem de vergetação natural e não natural do municipio escolhido e o grafico donut com os rankings dos 5 municipios que mais desmatam.

**Comment by alanagabriele** [comment]
Os temas dos gráficos foram: Desmatamento e vegetação

**Comment by alanagabriele** [comment]
Os gráficos foram implementados de forma intuitiva e esta acessivel no site: https://desmatazonia.netlify.app/
