### ISSUE TITLE
Estudo e Início da Reimplementação dos Gráficos

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#58]
**Descrição:**
Estamos iniciando um processo de aprimoramento dos gráficos em nossa aplicação, visando melhorar a experiência do usuário e fornecer representações visuais mais eficazes dos dados. Esta issue servirá como um ponto central para o estudo e planejamento da reimplementação dos gráficos.

**Tarefas:**

- [x] **Alinhar a Nova Base de Dados:** Garantir que a nova base de dados esteja alinhada corretamente com as informações que serão exibidas em cada gráfico.

- [x] **Estudo e Análise de Implementação:** Realizar um estudo aprofundado sobre como os novos gráficos serão implementados, analisando diferentes abordagens e tecnologias.

- [x] **Ajustar o Filtro de Busca:** Melhorar o filtro de busca dos gráficos para garantir uma experiência de usuário mais eficiente.

- [x] **Implementação no Frontend:** Iniciar a implementação dos novos gráficos no frontend da aplicação.

**Observações:**
- Manter a compatibilidade com as versões anteriores da aplicação, se aplicável.
- Documentar as decisões tomadas durante o processo de estudo e implementação.
- Design responsivo para diferentes tamanhos de tela deve ser considerado.

**Comment by alanagabriele** [comment]
Todos os requisitos da issue foram realizados no gráfico. 
Url do site: https://desmatazonia.netlify.app/

**Comment by SkywalkerSupreme** [comment]
Estou animado para começar o estudo sobre as diferentes abordagens para a implementação dos novos gráficos. Vou analisar as tecnologias disponíveis, levando em conta aspectos como desempenho e escalabilidade. Farei o possível para documentar minhas conclusões de forma clara para o benefício da equipe.
