### ISSUE TITLE
Atualização e Correção do Front

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#59]
**Descrição:**
Esta issue tem como objetivo realizar atualizações e correções no frontend da aplicação para melhorar a disposição dos gráficos, elementos e adicionar um menu de informações.

**Tarefas:**

1. [x] **Ajustar a Disposição dos Gráficos:** Realizar ajustes na disposição dos gráficos para otimizar a visualização e a experiência do usuário.

2. [x] **Ajustar a Disposição dos Elementos do Front:** Reorganizar a disposição dos elementos no frontend, garantindo uma interface mais coesa e intuitiva.

3. [x] **Criação do Menu de Informações:** Implementar um menu de informações para fornecer detalhes adicionais e aprimorar a navegação na aplicação.

**Observações:**
- Manter a consistência visual em toda a aplicação.
- Testar as alterações em diferentes dispositivos para garantir responsividade.
- Documentar qualquer decisão de design ou arquitetura durante o processo.

**Comment by daramariabs** [comment]
Atualizei o front com o que julguei ser necessário para o trabalho.
