### ISSUE TITLE
Pesquisar sobre Projetos Open Source

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#6]
# Objetivo
No decorrer do nosso trabalho, iremos precisar saber como um projeto Open Source funciona, então seria interessante pesquisar detalhes sobre boas práticas, como os repositórios são geralmente organizados e quaisquer outras coisas que possam vir a impactar positivamente no trabalho.
#Atividades

**Comment by acamposs** [comment]
# O que é Open Source?

O termo "open source" significa, literalmente, "código aberto" em inglês. Mas o que diabos isso quer dizer? Vamos imaginar um software (programa de computador) como um sanduíche gigante. Normalmente, você não pode ver o que está dentro do seu sanduíche favorito; você apenas come e aproveita. Mas, com o open source, é como se alguém lhe desse a receita secreta do sanduíche! Todos podem ver como é feito, mudar os ingredientes e até mesmo compartilhar sua própria versão do sanduíche com o mundo.

 ## A História por Trás do Open Source

A história do open source começa com pessoas que acreditam que compartilhar é se importar. Imagine um grupo de amigos que adora cozinhar. Eles percebem que, se compartilharem suas receitas e dicas uns com os outros, todos podem aprender a cozinhar melhor. É mais ou menos isso que aconteceu no mundo da tecnologia. As pessoas perceberam que, se compartilharem o código-fonte de seus programas de computador, todos podem se beneficiar e criar coisas incríveis juntos.

## Por que Open Source é Incrível?

Aqui está a parte realmente empolgante: o open source é como um grande parque de diversões para pessoas que amam tecnologia. Quando você usa um software open source, você tem a liberdade de:

Explorar: Você pode ver como tudo funciona. Como um mágico revelando seus truques, você pode descobrir os segredos do software.

Personalizar: Assim como um chef ajusta a receita do seu sanduíche para seu gosto, você pode personalizar o software para atender às suas necessidades.

Compartilhar: Você pode pegar um pedaço do sanduíche, adicioná-lo ao seu e compartilhá-lo com o mundo. Isso ajuda a criar uma comunidade de pessoas que colaboram e melhoram o software constantemente.

## Exemplos do Mundo Real

Muitos dos programas que usamos todos os dias são open source, como o navegador web Firefox, o sistema operacional Linux e até mesmo o sistema Android em smartphones. Eles são como receitas secretas que todo mundo pode ver e usar!

## Conclusão

Então, aí está: open source é como uma festa onde todos são bem-vindos a cozinhar e experimentar. É uma filosofia incrível que torna a tecnologia mais acessível e divertida. Agora que você entende o que é open source, você pode se juntar a essa comunidade de chefs de tecnologia e começar a criar, compartilhar e explorar como nunca antes. É hora de abrir a caixa de ferramentas e mergulhar no mundo mágico do código aberto! 🚀👨‍💻🍔
