### ISSUE TITLE
Análise sobre a Documentação que Falta

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#61]
**Descrição:**
Esta issue tem como objetivo realizar uma análise abrangente da documentação existente, identificando lacunas e propondo melhorias para as documentações do GitPages (MkDocs), README e Release Notes.

**Tarefas:**

1. [x] **Análise do GitPages (MkDocs):** Revisar a documentação no GitPages e identificar áreas que precisam ser aprimoradas ou adicionadas para garantir uma referência completa e compreensível do projeto.

2. [x] **Análise do README:** Verificar o README do projeto e identificar informações ausentes, descrições inadequadas ou qualquer outra melhoria necessária para facilitar a compreensão e contribuição.

3. [x] **Análise das Release Notes:** Examinar as Release Notes e assegurar que todas as versões anteriores e atuais estejam documentadas de forma clara, destacando as principais alterações em cada versão.

4. [ ] **Inclusão de Instruções de Contribuição:** Se necessário, adicionar instruções claras sobre como os colaboradores podem contribuir para o projeto, seja na documentação ou no código.

5. [ ] **Atualização de Exemplos e Demonstração:** Rever e atualizar exemplos e demonstrações presentes na documentação para garantir que estejam alinhados com as últimas alterações e funcionalidades do projeto.

7. [x] **Adicionar a documentação que falta:** Existem alguns relatórios que estão faltando, como a evolução do projeto e sobre como foi a dinâmica do grupo com a metodologia ágil.

**Observações:**
- Certificar-se de que a linguagem utilizada na documentação seja clara e compreensível.
- Incluir links entre as diferentes seções da documentação para facilitar a navegação.

**Comment by SkywalkerSupreme** [comment]
Estou nos últimos dias dedicada à atualização da documentação e gostaria de compartilhar o progresso. Atualmente, estou focada na análise do grupo diante da metodologia ágil, revisando como nos adaptamos e aprendemos ao longo do desenvolvimento. Além disso, estou trabalhando na documentação sobre a evolução do projeto e dos protótipos, destacando as principais mudanças e aprendizados tivemos com o decorrer do tempo.

 Estão na branch Docs2
