### ISSUE TITLE
Atualização de Testes e Qualidade de Software

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#64]
**Objetivo:** 

Atualização relacionada aos testes e qualidade de software, incluindo informações sobre os testes implementados, a abordagem de qualidade adotada e instruções para manter essa seção atualizada.

**Tarefas:**

   - [x] Atualização relacionadas a Testes e Qualidade de Software.
   - [x] Incluir informações sobre os testes implementados e a abordagem de qualidade.
   - [x] Criar um manual detalhado sobre como manter a documentação de Testes e Qualidade atualizada.

**Observações:**

   - Garantir a qualidade de software em nosso projeto
   - Destacar os principais benefícios da abordagem de qualidade adotada.

**Comment by IsaqueSH** [comment]
## Importância dos Testes de Software

- **Identificação de falhas e bugs:** Encontrar e corrigir problemas no início do desenvolvimento economiza tempo e recursos.
  
- **Asseguram qualidade:** Garantem que o software atenda aos requisitos e expectativas do usuário.
  
- **Aumentam confiança:** Um software testado gera confiança nos usuários, aumentando a credibilidade da empresa ou desenvolvedor.
  
- **Economizam recursos a longo prazo:** Corrigir erros durante o desenvolvimento é mais barato do que após o lançamento.
  
- **Melhoram a experiência do usuário:** Softwares sem bugs proporcionam uma experiência mais satisfatória aos usuários.

Em suma, os testes de software são cruciais para garantir um produto de qualidade, evitar problemas futuros e satisfazer as necessidades dos usuários.

**Comment by acamposs** [comment]
documentei todos os testes na issue: 45 - Teste e Validação
