### ISSUE TITLE
Atualização de Percalços e Problemas no Release Notes

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#65]
**Objetivo:** 
Atualizar a seção de Release Notes com informações sobre os percalços e problemas enfrentados no desenvolvimento do projeto, garantindo que estejam bem documentados para futuras referências.

**Tarefas:**
   - [ ] Atualizar a seção de Release Notes com percalços e problemas enfrentados.
   - [ ] Documentar soluções ou abordagens para resolver os problemas mencionados.
   - [ ] Revisar e consolidar informações relevantes.

**Observações:**
   - Garantir que as soluções para problemas estejam claramente apresentadas.

**Comment by IsaqueSH** [comment]
## Importância das Release Notes

- **Comunicam mudanças:** Informam aos usuários sobre atualizações, correções e novas funcionalidades do software.
  
- **Transparência e Confiança:** Demonstram transparência da equipe de desenvolvimento, construindo confiança entre usuários e desenvolvedores.
  
- **Orientam os usuários:** Auxiliam na compreensão das mudanças e impactos da nova versão, facilitando a transição.
  
- **Registro Histórico:** Funcionam como um registro das evoluções do software ao longo do tempo.
  
- **Feedback e Melhoria:** Permitem receber feedback dos usuários para direcionar melhorias futuras.

Resumindo, as Release Notes são importantes para informar, orientar os usuários, manter transparência e possibilitar melhorias contínuas no software.
