### ISSUE TITLE
Atualização do GitPages (MkDocs)

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#66]
**Objetivo:** 
Revisar e atualizar o conteúdo no GitPages (MkDocs), garantindo que todas as informações estejam precisas e refletindo os desenvolvimentos mais recentes no projeto.

**Tarefas:**
   - [x] Revisar e atualizar todas as seções do GitPages (MkDocs).
   - [x] Garantir que as informações estejam alinhadas com as versões mais recentes do projeto.

**Observações:**
   - Incorporar exemplos visuais sempre que possível para melhorar a compreensão.

**Comment by acamposs** [comment]
foi observado a necessidade de fazer um gitpage para o usuario.

**Comment by IsaqueSH** [comment]
Foi decidido dividir nosso GitPages em suas seções, uma com um foco maior no usuário e outra contendo toda documentação do nosso projeto.
