### ISSUE TITLE
Atualização dos Readmes (Principal, Extrator e Front)

### ISSUE THREAD

**Issue by acamposs** [unb-mds/2023-2-Squad02-Desmatazonia#67]
**Objetivo:** 
Atualizar os Readmes principais, do Extrator e do Front-end, incluindo informações sobre as tecnologias utilizadas, instruções de instalação e execução, e garantindo que estejam alinhados com as últimas versões do projeto.

**Tarefas:**
   - [x] Atualizar as seções relevantes nos Readmes principais, do Extrator e do Front-end.
   - [x] Incluir informações sobre as tecnologias utilizadas.
   - [x] Criar instruções claras de instalação e execução.

**Observações:**
   - Destacar os requisitos mínimos para execução do projeto.

**Comment by acamposs** [comment]
os README's do extrator e do projeto foram atualizados.

peço algumas informações interessantes a respeito do site para que a atualização do README do front seja atualizado!

@IsaqueSH @Angelicahaas @alanagabriele

**Comment by SkywalkerSupreme** [comment]
Eu e o Isaque estamos fazendo revisando os readmes

**Comment by IsaqueSH** [comment]
Os Readmes foram atualizados!
