### ISSUE TITLE
Deploy do front

### ISSUE THREAD

**Issue by alanagabriele** [unb-mds/2023-2-Squad02-Desmatazonia#68]
Fazer o deploy do frontend para todos terem acesso

**Comment by IsaqueSH** [comment]
**Importância do deploy:**

É o processo de lançar uma versão atualizada ou nova de um software, permitindo que os usuários tenham acesso às melhorias, correções de bugs e novas funcionalidades. Essencial para manter a relevância e a qualidade do software.
