### ISSUE TITLE
Estudar sobre Arquitetura de Software

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#7]
# Objetivo
Estudar sobre o conteúdo passado em aula no dia 04/10 (quarta-feira).

**Comment by SkywalkerSupreme** [comment]
Gente, eu achei esses sites aqui e são bem bacanas:

https://arquiteturadesoftware.online/

https://www.devmedia.com.br/arquitetura-de-software-desenvolvimento-orientado-para-arquitetura/8033
