### ISSUE TITLE
Documentação do Projeto

### ISSUE THREAD

**Issue by souzagusta** [unb-mds/2023-2-Squad02-Desmatazonia#9]
# Objetivo
A documentação é uma das partes mais importantes em qualquer projeto. Ela é geralmente a primeira coisa que qualquer pessoa interessada no trabalho irá ler, e deve ser organizada e objetiva, ao mesmo tempo em que explica com detalhes sobre as funcionalidades e demais detalhes de implementação. O projeto atual deve ser documentado, sendo o grupo o responsável por construir e manter essa documentação. 
# Atividades
- [x] Pesquisar sobre documentação. Em que consiste, como documentar software
- [x] Disponibilizar links e demais materiais de relevância
- [x] Iniciar a documentação do código do projeto

**Comment by IsaqueSH** [comment]
Um bom site para aprender um pouco sobre mkdocs(onde iremos trabalhar com nossas documentações)
--
https://squidfunk.github.io/mkdocs-material/getting-started/
